-- =========================================
-- 99_drop_tables.sql
-- 実行ユーザー：CREEPY
-- 内容：T-01〜T-15 の全テーブルを削除する（作り直し用）
--       子テーブルから順に削除する
--
-- ※ 現時点では実行しない（環境構築ではスキーマ作成 00 までにとどめる）
--    実行するとデータはすべて消え、元に戻せないので注意
-- =========================================

DROP TABLE CONVERSATION_LOGS CASCADE CONSTRAINTS PURGE;
DROP TABLE EVAL_COMMENTS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_EVALUATIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE PLAN_REVISIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE PLANNER_EVALUATIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE FILES CASCADE CONSTRAINTS PURGE;
DROP TABLE MESSAGES CASCADE CONSTRAINTS PURGE;
DROP TABLE PLAN_OPTIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE PLANS CASCADE CONSTRAINTS PURGE;
DROP TABLE ONBOARDING_ANSWERS CASCADE CONSTRAINTS PURGE;
DROP TABLE RESET_TOKENS CASCADE CONSTRAINTS PURGE;
DROP TABLE PRICE_MASTER CASCADE CONSTRAINTS PURGE;
DROP TABLE VISUAL_IMAGES CASCADE CONSTRAINTS PURGE;
DROP TABLE ARCHETYPE_MASTER CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS CASCADE CONSTRAINTS PURGE;
